/* =====================================================================
   BỘ NÃO · DINH DƯỠNG
   Bảng tra cứu món ăn Việt: calo, đạm, tinh bột, béo cho 1 phần thông thường.
   F(tên, khẩu phần, kcal, đạm, tinh bột, béo, nhóm, chế độ, dị ứng, [nhãn, lý do, gợi ý thay thế])
     nhóm   : xem FOOD_CATS
     chế độ : omni (có thịt/cá) | veg (chay, có trứng/sữa) | vegan (thuần chay)
     dị ứng : seafood dairy egg nuts gluten beef pork
     nhãn   : để trống thì bộ máy tự xếp ✅ nên ăn / ⚠️ hạn chế theo calo, đạm, đường, mỡ.
              Ghi 'good' hoặc 'limit' để ép nhãn, kèm lý do và gợi ý thay thế.
   ===================================================================== */
window.BRAIN = window.BRAIN || {};

BRAIN.FOOD_CATS = [
  {id: 'noodle', name: '🍜 Món nước'}, {id: 'rice', name: '🍚 Cơm'}, {id: 'bread', name: '🥖 Bánh mì, xôi, bánh Việt'},
  {id: 'protein', name: '🍗 Thịt, cá, trứng, đậu'}, {id: 'healthy', name: '🥗 Món healthy'}, {id: 'veg', name: '🥬 Rau, canh, củ'},
  {id: 'fruit', name: '🍌 Trái cây'}, {id: 'fastfood', name: '🍔 Fast food'}, {id: 'western', name: '🍝 Món Âu – Mỹ'},
  {id: 'japan', name: '🍣 Món Nhật'}, {id: 'korea', name: '🥘 Món Hàn'}, {id: 'asia', name: '🥟 Món Hoa – Thái – Ấn'},
  {id: 'bakery', name: '🧁 Bánh ngọt, tráng miệng'}, {id: 'drink', name: '🥤 Đồ uống, sữa'}, {id: 'snack', name: '🍿 Ăn vặt'}
];

BRAIN.FOOD_DB = (() => {
  const F = (n, unit, kcal, p, c, f, cat, diet, tags, flag, why, alt) => ({n, unit, kcal, p, c, f, cat, diet, tags: tags || [], flag: flag || null, why: why || '', alt: alt || ''});
  return [
    // ---------- Món nước ----------
    F('Phở bò', '1 tô', 450, 25, 60, 12, 'noodle', 'omni', ['beef'], null, '', 'Xin ít bánh, thêm rau, chừa nước béo'),
    F('Phở gà', '1 tô', 420, 25, 58, 9, 'noodle', 'omni', []),
    F('Phở chay', '1 tô', 380, 14, 62, 8, 'noodle', 'vegan', []),
    F('Bún bò Huế', '1 tô', 500, 25, 65, 15, 'noodle', 'omni', ['beef', 'pork'], null, '', 'Bỏ chả và giò heo, xin ít bún'),
    F('Bún chả', '1 phần', 550, 25, 65, 20, 'noodle', 'omni', ['pork'], null, '', 'Ăn nhiều rau, ít bún, ít nước chấm'),
    F('Bún thịt nướng', '1 tô', 520, 24, 65, 17, 'noodle', 'omni', ['pork', 'nuts'], null, '', 'Bỏ chả giò, ít mỡ hành'),
    F('Bún riêu cua', '1 tô', 420, 18, 55, 12, 'noodle', 'omni', ['seafood', 'pork']),
    F('Bún cá', '1 tô', 420, 24, 58, 9, 'noodle', 'omni', ['seafood']),
    F('Bún mọc', '1 tô', 430, 22, 58, 11, 'noodle', 'omni', ['pork']),
    F('Bún đậu mắm tôm', '1 mẹt', 650, 28, 70, 28, 'noodle', 'omni', ['pork', 'seafood'], null, '', 'Gọi đậu luộc thay đậu chiên, bớt chả cốm'),
    F('Hủ tiếu Nam Vang', '1 tô', 430, 22, 60, 10, 'noodle', 'omni', ['pork', 'seafood']),
    F('Hủ tiếu xào', '1 đĩa', 600, 18, 75, 25, 'noodle', 'omni', ['pork'], null, '', 'Chọn hủ tiếu nước'),
    F('Bánh canh cua', '1 tô', 480, 20, 65, 14, 'noodle', 'omni', ['seafood']),
    F('Mì Quảng', '1 tô', 480, 24, 62, 14, 'noodle', 'omni', ['nuts']),
    F('Miến gà', '1 tô', 400, 24, 55, 8, 'noodle', 'omni', []),
    F('Cháo gà', '1 tô', 320, 20, 42, 7, 'noodle', 'omni', []),
    F('Cháo lòng', '1 tô', 420, 18, 45, 18, 'noodle', 'omni', ['pork'], 'limit', 'Nhiều mỡ, nội tạng', 'Cháo gà, cháo cá'),
    F('Mì gói', '1 gói', 350, 7, 48, 14, 'noodle', 'veg', ['gluten'], 'limit', 'Nhiều muối, chiên sẵn, ít đạm', 'Bún, phở; nếu ăn thì thêm trứng và rau'),
    F('Mì xào bò', '1 đĩa', 650, 25, 70, 28, 'noodle', 'omni', ['beef', 'gluten'], null, '', 'Phở bò hoặc mì nước'),
    F('Lẩu', '1 phần', 600, 35, 40, 30, 'noodle', 'omni', [], null, '', 'Ăn nhiều rau, nấm, đạm; ít mì và nước lẩu béo'),

    // ---------- Cơm ----------
    F('Cơm tấm sườn', '1 đĩa', 650, 30, 80, 22, 'rice', 'omni', ['pork'], null, '', 'Bỏ mỡ hành, ít nước mắm, thêm dưa leo'),
    F('Cơm tấm sườn bì chả', '1 đĩa', 800, 35, 90, 32, 'rice', 'omni', ['pork', 'egg'], null, '', 'Chỉ gọi sườn, bỏ bì chả'),
    F('Cơm gà xối mỡ', '1 đĩa', 750, 32, 85, 30, 'rice', 'omni', [], null, '', 'Cơm gà luộc hoặc gà nướng'),
    F('Cơm gà luộc / gà xé', '1 đĩa', 580, 34, 75, 14, 'rice', 'omni', []),
    F('Cơm văn phòng (1 mặn 1 rau)', '1 phần', 600, 28, 80, 18, 'rice', 'omni', []),
    F('Cơm chiên dương châu', '1 đĩa', 700, 20, 90, 28, 'rice', 'omni', ['egg', 'pork'], null, '', 'Cơm trắng + món đạm luộc, kho'),
    F('Cơm bò lúc lắc', '1 đĩa', 680, 35, 75, 24, 'rice', 'omni', ['beef'], null, '', 'Đổi khoai tây chiên sang salad'),
    F('Cơm chay thập cẩm', '1 đĩa', 520, 16, 80, 14, 'rice', 'vegan', []),
    F('Cơm trắng', '1 chén (150g)', 200, 4, 45, 0.4, 'rice', 'vegan', []),
    F('Cơm gạo lứt', '1 chén (150g)', 180, 4, 38, 1.5, 'rice', 'vegan', [], 'good', 'Nhiều xơ, no lâu hơn cơm trắng'),

    // ---------- Bánh mì, xôi, bánh ----------
    F('Bánh mì thịt', '1 ổ', 400, 18, 50, 14, 'bread', 'omni', ['pork', 'gluten'], null, '', 'Ít pate, ít bơ, thêm rau'),
    F('Bánh mì trứng', '1 ổ', 380, 15, 45, 15, 'bread', 'veg', ['egg', 'gluten']),
    F('Bánh mì gà xé', '1 ổ', 400, 22, 48, 12, 'bread', 'omni', ['gluten']),
    F('Bánh mì chả cá', '1 ổ', 420, 18, 50, 15, 'bread', 'omni', ['seafood', 'gluten']),
    F('Xôi gà', '1 gói', 500, 20, 70, 15, 'bread', 'omni', [], null, '', 'Xin nửa phần xôi, giữ phần gà'),
    F('Xôi mặn thập cẩm', '1 gói', 600, 18, 80, 22, 'bread', 'omni', ['pork', 'egg'], null, '', 'Xôi gà, nửa phần xôi'),
    F('Xôi đậu xanh', '1 gói', 400, 10, 75, 6, 'bread', 'vegan', []),
    F('Bánh cuốn', '1 đĩa', 380, 14, 55, 11, 'bread', 'omni', ['pork']),
    F('Bánh bao nhân thịt', '1 cái', 300, 11, 40, 10, 'bread', 'omni', ['pork', 'gluten', 'egg']),
    F('Bánh xèo', '1 cái', 450, 14, 40, 26, 'bread', 'omni', ['seafood', 'pork'], null, '', 'Gỏi cuốn'),
    F('Bánh tráng nướng', '1 cái', 300, 8, 35, 14, 'bread', 'omni', ['egg']),
    F('Gỏi cuốn tôm thịt', '1 cuốn', 65, 3.5, 9, 1, 'bread', 'omni', ['seafood', 'pork'], 'good', 'Ít calo, nhiều rau'),
    F('Chả giò', '1 cuốn', 120, 4, 8, 8, 'bread', 'omni', ['pork'], 'limit', 'Chiên ngập dầu', 'Gỏi cuốn'),

    // ---------- Thịt, cá, trứng, đậu ----------
    F('Ức gà luộc / áp chảo', '100g', 165, 31, 0, 3.6, 'protein', 'omni', []),
    F('Đùi gà bỏ da', '100g', 180, 25, 0, 8, 'protein', 'omni', []),
    F('Thịt heo nạc', '100g', 143, 21, 0, 6, 'protein', 'omni', ['pork']),
    F('Thịt ba chỉ', '100g', 518, 9, 0, 53, 'protein', 'omni', ['pork'], null, '', 'Thịt nạc, nạc vai'),
    F('Sườn nướng', '1 miếng', 300, 22, 6, 20, 'protein', 'omni', ['pork'], null, '', 'Thịt nạc nướng'),
    F('Thịt bò nạc', '100g', 180, 26, 0, 8, 'protein', 'omni', ['beef']),
    F('Cá basa', '100g', 120, 18, 0, 5, 'protein', 'omni', ['seafood']),
    F('Cá hồi', '100g', 208, 20, 0, 13, 'protein', 'omni', ['seafood']),
    F('Cá thu', '100g', 200, 22, 0, 12, 'protein', 'omni', ['seafood']),
    F('Tôm', '100g', 100, 24, 0, 0.3, 'protein', 'omni', ['seafood']),
    F('Mực', '100g', 92, 16, 3, 1.4, 'protein', 'omni', ['seafood']),
    F('Trứng gà luộc', '1 quả', 75, 6, 0.6, 5, 'protein', 'veg', ['egg']),
    F('Trứng chiên', '1 quả', 110, 6, 0.6, 9, 'protein', 'veg', ['egg']),
    F('Trứng vịt lộn', '1 quả', 180, 13, 4, 12, 'protein', 'omni', ['egg']),
    F('Đậu hũ', '100g', 76, 8, 1.9, 4.8, 'protein', 'vegan', []),
    F('Đậu hũ chiên', '100g', 270, 17, 10, 20, 'protein', 'vegan', [], null, '', 'Đậu hũ non, đậu hũ hấp'),
    F('Tempeh', '100g', 190, 19, 9, 11, 'protein', 'vegan', []),
    F('Đậu nành Nhật (edamame)', '100g', 120, 11, 9, 5, 'protein', 'vegan', []),
    F('Đậu lăng / đậu gà (chín)', '1 chén', 230, 18, 40, 1, 'protein', 'vegan', []),
    F('Chả lụa', '100g', 220, 14, 2, 17, 'protein', 'omni', ['pork'], 'limit', 'Chế biến sẵn, nhiều muối', 'Thịt nạc luộc'),
    F('Xúc xích', '1 cây', 150, 6, 3, 13, 'protein', 'omni', ['pork'], 'limit', 'Chế biến sẵn, nhiều mỡ và muối', 'Trứng luộc, ức gà'),
    F('Whey protein', '1 muỗng', 120, 24, 3, 1.5, 'protein', 'veg', ['dairy']),
    F('Đạm thực vật (pea protein)', '1 muỗng', 110, 20, 2, 2, 'protein', 'vegan', []),

    // ---------- Món healthy tự nấu ----------
    F('Cơm + ức gà áp chảo + rau luộc', '1 phần', 520, 40, 60, 10, 'healthy', 'omni', []),
    F('Cơm gạo lứt + cá hấp + canh rau', '1 phần', 480, 30, 62, 10, 'healthy', 'omni', ['seafood']),
    F('Khoai lang + ức gà + salad', '1 phần', 420, 38, 40, 10, 'healthy', 'omni', []),
    F('Salad cá hồi + trứng', '1 phần', 450, 32, 12, 30, 'healthy', 'omni', ['seafood', 'egg']),
    F('Bún gạo lứt + gà xé + rau', '1 phần', 450, 32, 55, 9, 'healthy', 'omni', []),
    F('Ức gà xào nấm + bông cải', '1 phần', 380, 38, 20, 14, 'healthy', 'omni', []),
    F('Thịt bò áp chảo + khoai tây + salad', '1 phần', 540, 38, 45, 20, 'healthy', 'omni', ['beef']),
    F('Đậu hũ sốt cà + cơm + rau', '1 phần', 480, 18, 68, 14, 'healthy', 'vegan', []),
    F('Tempeh áp chảo + khoai lang + rau', '1 phần', 480, 28, 50, 18, 'healthy', 'vegan', []),
    F('Cơm + đậu hũ kho nấm + edamame', '1 phần', 520, 30, 60, 17, 'healthy', 'vegan', []),
    F('Trứng hấp nấm + đậu hũ', '1 phần', 250, 20, 6, 15, 'healthy', 'veg', ['egg']),
    F('Yến mạch + sữa chua Hy Lạp + trái cây', '1 tô', 330, 18, 50, 6, 'healthy', 'veg', ['dairy']),
    F('Sinh tố whey + chuối', '1 ly', 300, 26, 40, 3, 'healthy', 'veg', ['dairy']),

    // ---------- Rau, canh, củ ----------
    F('Rau luộc / xào ít dầu', '1 đĩa', 60, 3, 8, 2, 'veg', 'vegan', []),
    F('Rau muống xào tỏi', '1 đĩa', 150, 4, 8, 11, 'veg', 'vegan', []),
    F('Salad trộn dầu giấm', '1 đĩa', 120, 3, 10, 8, 'veg', 'vegan', []),
    F('Canh rau', '1 tô', 50, 2, 6, 2, 'veg', 'vegan', []),
    F('Canh chua cá', '1 tô', 150, 15, 10, 5, 'veg', 'omni', ['seafood']),
    F('Khoai lang luộc', '100g', 86, 1.6, 20, 0.1, 'veg', 'vegan', [], 'good', 'Tinh bột chậm, nhiều xơ'),
    F('Khoai tây luộc', '100g', 87, 2, 20, 0.1, 'veg', 'vegan', []),
    F('Khoai tây chiên', '1 phần vừa', 365, 4, 48, 17, 'veg', 'vegan', [], 'limit', 'Chiên ngập dầu', 'Khoai tây luộc, khoai lang'),
    F('Bắp luộc', '1 trái', 180, 5, 40, 2, 'veg', 'vegan', []),
    F('Yến mạch', '40g', 150, 5, 27, 2.5, 'veg', 'vegan', [], 'good', 'Tinh bột chậm, no lâu'),
    F('Bánh mì nguyên cám', '1 lát', 80, 4, 14, 1, 'veg', 'vegan', ['gluten'], 'good', 'Nhiều xơ hơn bánh mì trắng'),
    F('Bún tươi', '100g', 110, 2, 25, 0, 'veg', 'vegan', []),

    // ---------- Trái cây ----------
    F('Chuối', '1 quả', 105, 1.3, 27, 0.4, 'fruit', 'vegan', []),
    F('Táo', '1 quả', 95, 0.5, 25, 0.3, 'fruit', 'vegan', []),
    F('Ổi', '1 quả', 70, 2.6, 15, 1, 'fruit', 'vegan', []),
    F('Cam', '1 quả', 60, 1, 15, 0.2, 'fruit', 'vegan', []),
    F('Thanh long', '½ trái', 60, 1, 14, 0.2, 'fruit', 'vegan', []),
    F('Dưa hấu', '1 miếng (300g)', 90, 2, 22, 0.5, 'fruit', 'vegan', []),
    F('Xoài', '1 quả', 200, 2.8, 50, 1.3, 'fruit', 'vegan', []),
    F('Mít', '100g', 95, 1.7, 23, 0.6, 'fruit', 'vegan', []),
    F('Sầu riêng', '1 múi lớn (100g)', 150, 1.5, 27, 5, 'fruit', 'vegan', [], null, '', 'Ăn 1–2 múi nhỏ'),
    F('Bơ', '½ trái', 160, 2, 9, 15, 'fruit', 'vegan', [], null, 'Chất béo tốt nhưng nhiều calo'),

    // ---------- Đồ uống, sữa ----------
    F('Nước lọc / trà không đường', '1 ly', 0, 0, 0, 0, 'drink', 'vegan', []),
    F('Cà phê đen không đường', '1 ly', 5, 0.3, 0, 0, 'drink', 'vegan', [], 'good', 'Gần như 0 calo'),
    F('Cà phê sữa đá', '1 ly', 150, 2, 25, 4, 'drink', 'veg', ['dairy'], null, '', 'Cà phê đen, ít sữa'),
    F('Bạc xỉu', '1 ly', 200, 4, 30, 7, 'drink', 'veg', ['dairy'], 'limit', 'Nhiều sữa đặc, nhiều đường', 'Cà phê đen + chút sữa tươi'),
    F('Trà sữa trân châu', '1 ly size M', 350, 3, 60, 10, 'drink', 'veg', ['dairy'], 'limit', 'Nhiều đường, trân châu nhiều calo', 'Size S, 30% đường, bỏ trân châu'),
    F('Trà đào / trà chanh', '1 ly', 150, 0, 38, 0, 'drink', 'vegan', [], null, '', 'Trà không đường'),
    F('Nước ngọt có ga', '1 lon', 140, 0, 39, 0, 'drink', 'vegan', [], null, '', 'Nước có ga không đường, bản zero'),
    F('Nước ngọt zero', '1 lon', 1, 0, 0, 0, 'drink', 'vegan', []),
    F('Nước ép cam', '1 ly', 110, 2, 26, 0.5, 'drink', 'vegan', [], null, '', 'Ăn nguyên trái cam'),
    F('Sinh tố bơ', '1 ly', 350, 5, 45, 18, 'drink', 'veg', ['dairy'], 'limit', 'Nhiều đường và sữa đặc', 'Sinh tố không đường'),
    F('Nước dừa', '1 trái', 60, 1, 14, 0, 'drink', 'vegan', []),
    F('Bia', '1 lon 330ml', 145, 1.6, 13, 0, 'drink', 'vegan', ['gluten'], 'limit', 'Calo rỗng, dễ ăn nhiều đồ nhậu', 'Tối đa 2 lon, xen kẽ nước lọc'),
    F('Sữa tươi không đường', '220ml', 140, 7, 10, 8, 'drink', 'veg', ['dairy']),
    F('Sữa tươi có đường', '180ml', 140, 5, 20, 5, 'drink', 'veg', ['dairy'], null, '', 'Sữa không đường'),
    F('Sữa chua không đường', '1 hũ', 60, 4, 6, 2, 'drink', 'veg', ['dairy']),
    F('Sữa chua Hy Lạp', '1 hũ 100g', 100, 10, 4, 4, 'drink', 'veg', ['dairy']),
    F('Sữa đậu nành không đường', '1 hộp', 110, 7, 8, 5, 'drink', 'vegan', []),

    // ---------- Ăn vặt, đồ ngọt ----------
    F('Bánh tráng trộn', '1 bịch', 350, 6, 55, 12, 'snack', 'omni', ['egg'], 'limit', 'Nhiều tinh bột, dầu, ít đạm', 'Gỏi cuốn, trái cây'),
    F('Chè', '1 ly', 300, 5, 60, 5, 'bakery', 'vegan', [], 'limit', 'Nhiều đường', 'Sữa chua + trái cây'),
    F('Bánh flan', '1 cái', 130, 4, 20, 4, 'bakery', 'veg', ['egg', 'dairy']),
    F('Kem', '1 cây / viên', 200, 3, 24, 11, 'bakery', 'veg', ['dairy'], 'limit', 'Nhiều đường và béo', 'Sữa chua đông lạnh, trái cây đông lạnh'),
    F('Bánh kem', '1 miếng', 350, 4, 45, 18, 'bakery', 'veg', ['gluten', 'egg', 'dairy'], 'limit', 'Nhiều đường và bơ', 'Trái cây, sữa chua'),
    F('Snack khoai tây', '1 gói 30g', 160, 2, 15, 10, 'snack', 'vegan', [], 'limit', 'Chiên, nhiều muối, dễ ăn quá tay', 'Bắp luộc, hạt rang không muối'),
    F('Kẹo / socola sữa', '1 thanh', 230, 3, 26, 13, 'snack', 'veg', ['dairy', 'nuts'], 'limit', 'Nhiều đường', 'Socola đen 70%, 1–2 miếng'),
    F('Bắp rang bơ', '1 hộp vừa', 400, 5, 45, 22, 'snack', 'veg', ['dairy'], 'limit', 'Nhiều bơ và đường', 'Bắp luộc'),
    F('Hạt điều / hạnh nhân', '30g', 170, 5, 9, 14, 'snack', 'vegan', ['nuts'], null, 'Chất béo tốt nhưng nhiều calo, ăn 1 nắm nhỏ'),
    F('Đậu phộng rang', '30g', 170, 7, 5, 14, 'snack', 'vegan', ['nuts']),

    /* ===================== MỞ RỘNG ===================== */
    // ---------- Món nước Việt (thêm) ----------
    F('Phở cuốn', '1 phần (4 cuốn)', 350, 20, 40, 12, 'noodle', 'omni', ['beef']),
    F('Phở xào', '1 đĩa', 650, 25, 75, 26, 'noodle', 'omni', ['beef'], null, '', 'Phở nước'),
    F('Phở trộn', '1 tô', 500, 24, 65, 15, 'noodle', 'omni', ['beef', 'nuts']),
    F('Bún mắm', '1 tô', 550, 28, 65, 18, 'noodle', 'omni', ['seafood', 'pork']),
    F('Bún bò Nam Bộ', '1 tô', 520, 28, 60, 18, 'noodle', 'omni', ['beef', 'nuts']),
    F('Bún ốc', '1 tô', 400, 18, 55, 10, 'noodle', 'omni', ['seafood']),
    F('Bún chả cá', '1 tô', 450, 24, 60, 12, 'noodle', 'omni', ['seafood']),
    F('Bún măng vịt', '1 tô', 480, 26, 55, 16, 'noodle', 'omni', []),
    F('Bún thang', '1 tô', 420, 22, 55, 12, 'noodle', 'omni', ['egg', 'pork']),
    F('Bún mọc sườn', '1 tô', 480, 24, 58, 16, 'noodle', 'omni', ['pork']),
    F('Bún hến', '1 tô', 380, 18, 55, 9, 'noodle', 'omni', ['seafood', 'nuts']),
    F('Bánh canh ghẹ', '1 tô', 520, 24, 68, 16, 'noodle', 'omni', ['seafood']),
    F('Bánh canh giò heo', '1 tô', 560, 25, 65, 22, 'noodle', 'omni', ['pork'], null, '', 'Bánh canh cá, gà'),
    F('Hủ tiếu gõ', '1 tô nhỏ', 350, 15, 50, 9, 'noodle', 'omni', ['pork']),
    F('Hủ tiếu bò kho', '1 tô', 550, 30, 60, 20, 'noodle', 'omni', ['beef']),
    F('Mì vịt tiềm', '1 tô', 650, 30, 65, 28, 'noodle', 'omni', ['gluten'], null, '', 'Bỏ da vịt, ít nước dùng'),
    F('Mì hoành thánh', '1 tô', 450, 20, 60, 14, 'noodle', 'omni', ['pork', 'gluten', 'egg', 'seafood']),
    F('Mì xào giòn hải sản', '1 đĩa', 700, 22, 80, 32, 'noodle', 'omni', ['seafood', 'gluten', 'egg'], null, '', 'Mì nước hải sản'),
    F('Cao lầu', '1 tô', 520, 24, 70, 15, 'noodle', 'omni', ['pork', 'gluten']),
    F('Bánh đa cua', '1 tô', 450, 18, 60, 14, 'noodle', 'omni', ['seafood']),
    F('Miến lươn', '1 tô', 450, 20, 60, 14, 'noodle', 'omni', ['seafood']),
    F('Miến xào cua', '1 đĩa', 550, 18, 75, 18, 'noodle', 'omni', ['seafood', 'egg']),
    F('Cháo vịt', '1 tô', 450, 25, 40, 20, 'noodle', 'omni', []),
    F('Cháo sườn', '1 tô', 380, 15, 50, 12, 'noodle', 'omni', ['pork']),
    F('Cháo cá', '1 tô', 320, 22, 42, 6, 'noodle', 'omni', ['seafood']),
    F('Cháo trắng + trứng muối', '1 tô', 280, 9, 45, 7, 'noodle', 'veg', ['egg']),
    F('Súp cua', '1 chén', 180, 10, 18, 7, 'noodle', 'omni', ['seafood', 'egg']),
    F('Lẩu Thái hải sản', '1 phần', 550, 35, 30, 30, 'noodle', 'omni', ['seafood'], null, '', 'Ăn nhiều rau, ít mì, ít nước lẩu'),
    F('Lẩu bò', '1 phần', 650, 40, 30, 38, 'noodle', 'omni', ['beef'], null, '', 'Chọn thịt nạc, nhiều rau'),
    F('Lẩu gà lá é', '1 phần', 550, 40, 30, 28, 'noodle', 'omni', []),
    F('Lẩu mắm', '1 phần', 650, 35, 35, 38, 'noodle', 'omni', ['seafood', 'pork']),

    // ---------- Cơm Việt (thêm) ----------
    F('Cơm gà Hải Nam', '1 đĩa', 650, 32, 80, 22, 'rice', 'omni', []),
    F('Cơm sườn xào chua ngọt', '1 phần', 700, 28, 85, 26, 'rice', 'omni', ['pork']),
    F('Cơm thịt kho trứng', '1 phần', 700, 30, 80, 28, 'rice', 'omni', ['pork', 'egg']),
    F('Cơm cá kho tộ', '1 phần', 600, 30, 80, 16, 'rice', 'omni', ['seafood']),
    F('Cơm đùi gà chiên', '1 đĩa', 750, 35, 80, 32, 'rice', 'omni', [], null, '', 'Cơm gà luộc / gà nướng'),
    F('Cơm chiên hải sản', '1 đĩa', 680, 25, 85, 24, 'rice', 'omni', ['seafood', 'egg']),
    F('Cơm rang dưa bò', '1 đĩa', 700, 28, 85, 26, 'rice', 'omni', ['beef']),
    F('Cơm bò xào rau', '1 đĩa', 620, 30, 80, 18, 'rice', 'omni', ['beef']),
    F('Cơm niêu cá kho', '1 phần', 650, 30, 85, 20, 'rice', 'omni', ['seafood']),
    F('Cơm hến', '1 tô', 400, 18, 60, 10, 'rice', 'omni', ['seafood', 'nuts']),
    F('Cơm cháy chà bông', '1 phần', 450, 10, 60, 18, 'rice', 'omni', ['pork'], 'limit', 'Chiên, nhiều dầu', 'Cơm gạo lứt + đạm'),
    F('Cơm sườn nướng + trứng ốp', '1 đĩa', 780, 38, 82, 32, 'rice', 'omni', ['pork', 'egg'], null, '', 'Bỏ trứng chiên, thêm rau'),
    F('Cơm gà xào sả ớt', '1 đĩa', 620, 32, 80, 18, 'rice', 'omni', []),
    F('Cơm đậu hũ dồn thịt', '1 phần', 620, 26, 80, 20, 'rice', 'omni', ['pork']),

    // ---------- Bánh Việt (thêm) ----------
    F('Bánh mì heo quay', '1 ổ', 500, 20, 50, 24, 'bread', 'omni', ['pork', 'gluten']),
    F('Bánh mì xíu mại', '1 ổ', 480, 20, 55, 18, 'bread', 'omni', ['pork', 'gluten']),
    F('Bánh mì que', '1 cây', 220, 7, 28, 9, 'bread', 'omni', ['pork', 'gluten']),
    F('Bánh mì chảo', '1 phần', 650, 30, 50, 36, 'bread', 'omni', ['egg', 'pork', 'beef', 'gluten'], null, '', 'Bánh mì trứng ít bơ'),
    F('Bánh mì sandwich trắng', '1 lát', 70, 2.5, 13, 1, 'bread', 'vegan', ['gluten']),
    F('Bánh giò', '1 cái', 350, 10, 45, 14, 'bread', 'omni', ['pork']),
    F('Bánh bèo', '1 đĩa', 300, 8, 50, 7, 'bread', 'omni', ['seafood']),
    F('Bánh bột lọc', '10 cái', 350, 10, 60, 7, 'bread', 'omni', ['seafood', 'pork']),
    F('Bánh khọt', '8 cái', 450, 12, 40, 26, 'bread', 'omni', ['seafood'], null, '', 'Ăn nhiều rau, ít bánh'),
    F('Bánh căn', '1 phần', 400, 14, 55, 12, 'bread', 'omni', ['egg', 'seafood']),
    F('Bánh hỏi heo quay', '1 phần', 550, 22, 60, 24, 'bread', 'omni', ['pork']),
    F('Bánh ướt', '1 đĩa', 350, 10, 60, 6, 'bread', 'omni', ['pork']),
    F('Bánh chưng', '¼ cái', 350, 10, 55, 10, 'bread', 'omni', ['pork']),
    F('Bánh đúc nóng', '1 chén', 300, 8, 45, 9, 'bread', 'omni', ['pork']),
    F('Bột chiên', '1 đĩa', 500, 10, 60, 24, 'bread', 'veg', ['egg'], null, '', 'Bánh cuốn, bánh ướt'),
    F('Nem nướng cuốn', '1 phần', 450, 22, 50, 16, 'bread', 'omni', ['pork', 'nuts']),
    F('Bò bía', '1 cuốn', 100, 4, 14, 3, 'bread', 'omni', ['pork', 'egg']),
    F('Bánh tráng cuốn thịt heo', '1 phần', 450, 25, 50, 14, 'bread', 'omni', ['pork']),
    F('Xôi xéo', '1 gói', 450, 10, 75, 12, 'bread', 'vegan', []),
    F('Xôi lạc', '1 gói', 450, 12, 70, 14, 'bread', 'vegan', ['nuts']),
    F('Xôi gấc', '1 gói', 400, 7, 80, 6, 'bread', 'vegan', []),
    F('Bánh bao chay', '1 cái', 220, 6, 42, 3, 'bread', 'vegan', ['gluten']),

    // ---------- Thịt, cá, trứng (thêm) ----------
    F('Gà nướng', '¼ con', 350, 35, 0, 23, 'protein', 'omni', []),
    F('Gà luộc', '100g', 200, 27, 0, 10, 'protein', 'omni', []),
    F('Gà xé phay', '1 đĩa', 300, 35, 8, 14, 'protein', 'omni', []),
    F('Vịt quay', '100g', 340, 19, 0, 29, 'protein', 'omni', [], 'limit', 'Da vịt nhiều mỡ', 'Bỏ da, ăn phần nạc'),
    F('Thịt heo quay', '100g', 400, 20, 0, 35, 'protein', 'omni', ['pork'], 'limit', 'Nhiều mỡ', 'Thịt heo luộc nạc'),
    F('Thịt luộc (nạc vai)', '100g', 200, 24, 0, 11, 'protein', 'omni', ['pork']),
    F('Thịt kho trứng', '1 phần', 450, 25, 8, 35, 'protein', 'omni', ['pork', 'egg'], 'limit', 'Nhiều mỡ', 'Thịt nạc kho, bỏ phần mỡ'),
    F('Bò kho', '1 tô', 450, 30, 15, 30, 'protein', 'omni', ['beef']),
    F('Bò lá lốt', '5 cuốn', 350, 20, 6, 27, 'protein', 'omni', ['beef', 'nuts']),
    F('Bò viên', '5 viên', 200, 12, 6, 14, 'protein', 'omni', ['beef']),
    F('Cá kho tộ', '100g', 200, 20, 5, 11, 'protein', 'omni', ['seafood']),
    F('Cá chiên', '100g', 250, 20, 5, 16, 'protein', 'omni', ['seafood'], null, '', 'Cá hấp, cá nướng'),
    F('Cá ngừ hộp ngâm nước', '100g', 120, 26, 0, 1, 'protein', 'omni', ['seafood']),
    F('Chả cá', '100g', 180, 15, 10, 9, 'protein', 'omni', ['seafood']),
    F('Tôm rim', '100g', 150, 22, 6, 4, 'protein', 'omni', ['seafood']),
    F('Tôm nướng', '100g', 130, 25, 1, 3, 'protein', 'omni', ['seafood']),
    F('Mực nướng', '100g', 150, 25, 4, 4, 'protein', 'omni', ['seafood']),
    F('Ốc luộc', '1 đĩa (200g)', 180, 30, 6, 2, 'protein', 'omni', ['seafood']),
    F('Nghêu hấp sả', '1 đĩa', 150, 24, 6, 2, 'protein', 'omni', ['seafood']),
    F('Cua hấp', '1 con (250g)', 200, 38, 0, 3, 'protein', 'omni', ['seafood']),
    F('Hàu nướng mỡ hành', '6 con', 300, 18, 12, 20, 'protein', 'omni', ['seafood']),
    F('Ếch xào sả ớt', '1 đĩa', 300, 30, 6, 17, 'protein', 'omni', []),
    F('Lươn xào sả ớt', '1 đĩa', 350, 30, 8, 22, 'protein', 'omni', ['seafood']),
    F('Nem chua', '1 cái', 60, 4, 2, 4, 'protein', 'omni', ['pork']),
    F('Lạp xưởng', '1 cây', 230, 7, 8, 19, 'protein', 'omni', ['pork'], 'limit', 'Nhiều mỡ, đường và muối', 'Trứng, thịt nạc'),
    F('Pate', '50g', 160, 6, 2, 14, 'protein', 'omni', ['pork'], 'limit', 'Nhiều mỡ', 'Bỏ bớt pate khi ăn bánh mì'),
    F('Trứng cút luộc', '5 quả', 70, 6, 0, 5, 'protein', 'veg', ['egg']),
    F('Trứng ốp la', '1 quả', 90, 6, 0.6, 7, 'protein', 'veg', ['egg']),
    F('Ức gà xông khói / ức gà ăn liền', '100g', 120, 24, 2, 2, 'protein', 'omni', []),
    F('Đậu phụ non', '100g', 55, 5, 2, 3, 'protein', 'vegan', []),

    // ---------- Healthy (thêm) ----------
    F('Poke bowl cá hồi', '1 tô', 600, 35, 70, 20, 'healthy', 'omni', ['seafood']),
    F('Salad ức gà + quinoa', '1 tô', 450, 38, 40, 14, 'healthy', 'omni', []),
    F('Wrap gà nướng', '1 cuốn', 400, 30, 40, 12, 'healthy', 'omni', ['gluten']),
    F('Ức gà + gạo lứt + bông cải (meal prep)', '1 hộp', 500, 45, 50, 10, 'healthy', 'omni', []),
    F('Smoothie bowl', '1 tô', 350, 8, 65, 7, 'healthy', 'veg', ['dairy']),
    F('Overnight oats', '1 hũ', 350, 15, 50, 9, 'healthy', 'veg', ['dairy']),
    F('Salad cá ngừ', '1 đĩa', 300, 28, 12, 15, 'healthy', 'omni', ['seafood', 'egg']),
    F('Bò áp chảo + salad', '1 phần', 400, 38, 10, 22, 'healthy', 'omni', ['beef']),
    F('Đậu hũ + rau củ hấp', '1 phần', 250, 18, 15, 12, 'healthy', 'vegan', []),
    F('Cá basa hấp gừng + rau', '1 phần', 280, 30, 10, 12, 'healthy', 'omni', ['seafood']),

    // ---------- Rau, củ (thêm) ----------
    F('Bông cải xanh luộc', '1 chén', 55, 4, 11, 0.6, 'veg', 'vegan', []),
    F('Rau củ xào thập cẩm', '1 đĩa', 150, 5, 15, 8, 'veg', 'vegan', []),
    F('Cải thìa xào nấm', '1 đĩa', 120, 5, 10, 7, 'veg', 'vegan', []),
    F('Nấm xào', '1 đĩa', 130, 5, 8, 9, 'veg', 'vegan', []),
    F('Đậu que xào tỏi', '1 đĩa', 120, 4, 12, 7, 'veg', 'vegan', []),
    F('Salad dưa leo cà chua', '1 đĩa', 50, 2, 10, 0.5, 'veg', 'vegan', []),
    F('Dưa leo', '1 trái', 30, 1, 7, 0, 'veg', 'vegan', []),
    F('Cà rốt luộc', '1 chén', 55, 1, 13, 0.3, 'veg', 'vegan', []),
    F('Bí đỏ luộc', '1 chén', 50, 2, 12, 0, 'veg', 'vegan', []),
    F('Súp rau củ', '1 chén', 80, 3, 14, 1, 'veg', 'vegan', []),
    F('Canh bí đao', '1 tô', 60, 3, 8, 2, 'veg', 'omni', ['pork']),
    F('Canh cải thịt bằm', '1 tô', 120, 10, 6, 6, 'veg', 'omni', ['pork']),
    F('Canh mồng tơi mướp', '1 tô', 60, 3, 9, 1, 'veg', 'vegan', []),
    F('Dưa chua / dưa muối', '1 chén', 25, 1, 5, 0, 'veg', 'vegan', [], null, 'Nhiều muối, ăn vừa phải'),
    F('Khoai môn luộc', '100g', 112, 1.5, 26, 0.2, 'veg', 'vegan', []),
    F('Củ sắn / củ đậu', '100g', 38, 1, 9, 0.1, 'veg', 'vegan', []),

    // ---------- Trái cây (thêm) ----------
    F('Nho', '1 chén', 100, 1, 27, 0.2, 'fruit', 'vegan', []),
    F('Dứa / thơm', '1 chén', 80, 1, 22, 0.2, 'fruit', 'vegan', []),
    F('Đu đủ', '1 chén', 60, 0.7, 15, 0.4, 'fruit', 'vegan', []),
    F('Bưởi', '¼ trái', 80, 1.5, 20, 0, 'fruit', 'vegan', []),
    F('Chôm chôm', '10 trái', 120, 1, 30, 0.3, 'fruit', 'vegan', []),
    F('Vải', '10 trái', 120, 1.5, 30, 0.5, 'fruit', 'vegan', []),
    F('Nhãn', '1 chén', 110, 1.5, 28, 0, 'fruit', 'vegan', []),
    F('Dâu tây', '1 chén', 50, 1, 12, 0.5, 'fruit', 'vegan', []),
    F('Kiwi', '1 trái', 45, 0.8, 11, 0.4, 'fruit', 'vegan', []),
    F('Lê', '1 trái', 100, 0.6, 27, 0.2, 'fruit', 'vegan', []),
    F('Măng cụt', '3 trái', 75, 0.5, 18, 0.5, 'fruit', 'vegan', []),
    F('Mận / roi', '3 trái', 60, 0.5, 15, 0, 'fruit', 'vegan', []),
    F('Việt quất', '1 chén', 85, 1, 21, 0.5, 'fruit', 'vegan', []),
    F('Chuối sấy', '30g', 150, 1, 17, 10, 'fruit', 'vegan', [], 'limit', 'Sấy với dầu, nhiều calo', 'Chuối tươi'),
    F('Xoài sấy dẻo', '50g', 170, 1, 40, 0.5, 'fruit', 'vegan', [], 'limit', 'Nhiều đường', 'Xoài tươi'),

    // ---------- Fast food ----------
    F('Gà rán', '1 miếng đùi', 290, 20, 10, 19, 'fastfood', 'omni', ['gluten'], 'limit', 'Chiên ngập dầu', 'Bỏ da, hoặc gà nướng'),
    F('Combo gà rán (2 miếng + khoai + nước ngọt)', '1 combo', 1100, 45, 110, 52, 'fastfood', 'omni', ['gluten'], null, '', 'Bỏ nước ngọt, đổi khoai sang salad'),
    F('Burger bò', '1 cái', 500, 25, 40, 26, 'fastfood', 'omni', ['beef', 'gluten', 'dairy', 'egg'], null, '', 'Bỏ sốt mayo, không phô mai'),
    F('Cheeseburger', '1 cái', 300, 15, 32, 13, 'fastfood', 'omni', ['beef', 'gluten', 'dairy']),
    F('Burger gà giòn', '1 cái', 550, 25, 50, 28, 'fastfood', 'omni', ['gluten', 'egg'], null, '', 'Burger gà nướng'),
    F('Burger gà nướng', '1 cái', 400, 30, 40, 12, 'fastfood', 'omni', ['gluten']),
    F('Hot dog', '1 cái', 300, 11, 24, 18, 'fastfood', 'omni', ['pork', 'gluten']),
    F('Pizza phô mai', '1 miếng', 285, 12, 36, 10, 'fastfood', 'veg', ['gluten', 'dairy'], null, '', 'Ăn 1–2 miếng kèm salad'),
    F('Pizza hải sản', '1 miếng', 300, 14, 34, 12, 'fastfood', 'omni', ['seafood', 'gluten', 'dairy']),
    F('Pizza pepperoni', '1 miếng', 310, 13, 35, 13, 'fastfood', 'omni', ['pork', 'gluten', 'dairy']),
    F('Gà viên chiên (nuggets)', '6 viên', 280, 14, 16, 18, 'fastfood', 'omni', ['gluten']),
    F('Cánh gà chiên nước mắm', '5 cánh', 450, 30, 12, 30, 'fastfood', 'omni', []),
    F('Khoai tây chiên size lớn', '1 phần', 500, 6, 65, 24, 'fastfood', 'vegan', [], null, '', 'Size nhỏ, hoặc khoai nướng'),
    F('Hành tây chiên', '1 phần', 400, 5, 45, 22, 'fastfood', 'vegan', ['gluten']),
    F('Phô mai que', '5 que', 400, 16, 30, 24, 'fastfood', 'veg', ['dairy', 'gluten']),
    F('Sandwich gà nướng', '1 cái', 400, 30, 40, 12, 'fastfood', 'omni', ['gluten']),
    F('Sandwich cá ngừ', '1 cái', 450, 22, 40, 20, 'fastfood', 'omni', ['seafood', 'gluten', 'egg']),
    F('Sandwich trứng', '1 cái', 300, 14, 30, 13, 'fastfood', 'veg', ['egg', 'gluten']),
    F('Burrito bò', '1 cái', 650, 28, 80, 22, 'fastfood', 'omni', ['beef', 'dairy', 'gluten']),
    F('Taco', '1 cái', 200, 9, 15, 11, 'fastfood', 'omni', ['beef', 'dairy']),
    F('Kem sundae', '1 ly', 330, 7, 50, 11, 'fastfood', 'veg', ['dairy'], 'limit', 'Nhiều đường', 'Sữa chua + trái cây'),
    F('Mì ly / mì cốc', '1 ly', 300, 6, 40, 13, 'fastfood', 'veg', ['gluten'], 'limit', 'Nhiều muối, chiên sẵn', 'Thêm trứng và rau nếu ăn'),

    // ---------- Món Âu – Mỹ ----------
    F('Mì Ý sốt bò bằm (bolognese)', '1 đĩa', 650, 30, 80, 22, 'western', 'omni', ['beef', 'gluten']),
    F('Mì Ý sốt kem (carbonara)', '1 đĩa', 800, 28, 80, 40, 'western', 'omni', ['pork', 'dairy', 'egg', 'gluten'], null, '', 'Mì Ý sốt cà chua'),
    F('Mì Ý hải sản sốt cà chua', '1 đĩa', 600, 30, 80, 16, 'western', 'omni', ['seafood', 'gluten']),
    F('Mì Ý sốt pesto', '1 đĩa', 650, 18, 75, 30, 'western', 'veg', ['gluten', 'nuts', 'dairy']),
    F('Lasagna', '1 phần', 600, 30, 45, 32, 'western', 'omni', ['beef', 'dairy', 'gluten', 'egg']),
    F('Bít tết bò + khoai tây chiên', '1 phần', 850, 50, 50, 48, 'western', 'omni', ['beef'], null, '', 'Đổi khoai chiên sang salad / rau'),
    F('Bít tết bò + salad', '1 phần', 550, 50, 12, 32, 'western', 'omni', ['beef']),
    F('Bò bít tết (200g)', '200g', 500, 50, 0, 32, 'western', 'omni', ['beef']),
    F('Salad Caesar', '1 đĩa', 450, 12, 15, 38, 'western', 'omni', ['dairy', 'egg', 'gluten', 'seafood'], null, '', 'Xin sốt để riêng, thêm gà nướng'),
    F('Salad gà nướng', '1 đĩa', 350, 35, 15, 16, 'western', 'omni', []),
    F('Súp kem nấm', '1 chén', 250, 5, 20, 16, 'western', 'veg', ['dairy', 'gluten']),
    F('Súp bí đỏ', '1 chén', 180, 4, 25, 7, 'western', 'veg', ['dairy']),
    F('Cá hồi áp chảo + rau', '1 phần', 450, 35, 10, 30, 'western', 'omni', ['seafood']),
    F('Ức gà nướng + khoai nghiền', '1 phần', 550, 45, 40, 22, 'western', 'omni', ['dairy']),
    F('Sườn nướng BBQ', '1 phần', 700, 45, 30, 45, 'western', 'omni', ['pork'], null, '', 'Ăn nửa phần, thêm salad'),
    F('Gà nướng mật ong', '1 phần', 500, 40, 25, 26, 'western', 'omni', []),
    F('Mac & cheese', '1 phần', 500, 20, 50, 24, 'western', 'veg', ['dairy', 'gluten']),
    F('Risotto nấm', '1 đĩa', 550, 14, 75, 20, 'western', 'veg', ['dairy']),
    F('Bữa sáng kiểu Anh (trứng, xúc xích, bacon, bánh mì)', '1 phần', 750, 35, 45, 48, 'western', 'omni', ['pork', 'egg', 'gluten'], null, '', 'Trứng + bánh mì + rau, bỏ bacon'),
    F('Trứng ốp + bánh mì bơ', '1 phần', 400, 16, 30, 24, 'western', 'veg', ['egg', 'gluten', 'dairy']),
    F('Granola + sữa chua', '1 chén', 350, 12, 50, 12, 'western', 'veg', ['nuts', 'dairy']),
    F('Khoai tây nghiền', '1 chén', 230, 4, 35, 9, 'western', 'veg', ['dairy']),
    F('Bánh mì bơ tỏi', '2 lát', 300, 6, 30, 17, 'western', 'veg', ['gluten', 'dairy'], null, '', '1 lát thôi'),
    F('Fish & chips', '1 phần', 850, 30, 85, 44, 'western', 'omni', ['seafood', 'gluten'], null, '', 'Cá nướng + salad'),

    // ---------- Món Nhật ----------
    F('Sushi cá hồi (nigiri)', '1 miếng', 50, 2.5, 7, 1.2, 'japan', 'omni', ['seafood']),
    F('Sushi cá ngừ (nigiri)', '1 miếng', 45, 3, 7, 0.3, 'japan', 'omni', ['seafood']),
    F('Sushi cuộn California', '8 miếng', 260, 9, 38, 7, 'japan', 'omni', ['seafood', 'egg']),
    F('Sushi cuộn cá ngừ', '6 miếng', 200, 12, 30, 2, 'japan', 'omni', ['seafood']),
    F('Sushi cuộn tempura tôm', '8 miếng', 450, 12, 55, 20, 'japan', 'omni', ['seafood', 'gluten', 'egg']),
    F('Sushi trứng (tamago)', '2 miếng', 120, 5, 16, 4, 'japan', 'veg', ['egg']),
    F('Sashimi cá hồi', '5 lát (100g)', 210, 20, 0, 13, 'japan', 'omni', ['seafood']),
    F('Sashimi cá ngừ', '5 lát (100g)', 130, 28, 0, 1, 'japan', 'omni', ['seafood']),
    F('Ramen tonkotsu', '1 tô', 800, 30, 80, 38, 'japan', 'omni', ['pork', 'gluten', 'egg'], null, '', 'Ramen shoyu, chừa nước dùng'),
    F('Ramen shoyu', '1 tô', 550, 25, 75, 15, 'japan', 'omni', ['pork', 'gluten', 'egg']),
    F('Udon nước', '1 tô', 450, 15, 80, 6, 'japan', 'omni', ['gluten', 'seafood']),
    F('Soba lạnh', '1 phần', 350, 14, 70, 2, 'japan', 'vegan', ['gluten']),
    F('Mì xào Yakisoba', '1 đĩa', 600, 18, 80, 22, 'japan', 'omni', ['pork', 'gluten']),
    F('Tempura tôm', '5 con', 400, 18, 25, 24, 'japan', 'omni', ['seafood', 'gluten', 'egg'], null, '', 'Tôm nướng, sashimi'),
    F('Cơm cà ri Nhật', '1 đĩa', 750, 20, 100, 28, 'japan', 'omni', ['gluten', 'pork'], null, '', 'Nửa phần cơm, thêm salad'),
    F('Cơm heo chiên xù (katsudon)', '1 tô', 900, 35, 100, 38, 'japan', 'omni', ['pork', 'egg', 'gluten'], null, '', 'Cơm gà teriyaki'),
    F('Cơm bò Gyudon', '1 tô', 700, 28, 95, 22, 'japan', 'omni', ['beef']),
    F('Cơm gà Teriyaki', '1 phần', 650, 35, 85, 16, 'japan', 'omni', []),
    F('Cơm gà trứng (oyakodon)', '1 tô', 650, 32, 85, 18, 'japan', 'omni', ['egg']),
    F('Cơm lươn Nhật (unadon)', '1 tô', 750, 30, 95, 25, 'japan', 'omni', ['seafood']),
    F('Onigiri (cơm nắm)', '1 cái', 180, 4, 38, 1, 'japan', 'omni', ['seafood']),
    F('Takoyaki', '6 viên', 300, 10, 35, 13, 'japan', 'omni', ['seafood', 'gluten', 'egg']),
    F('Gyoza (há cảo chiên)', '6 cái', 300, 12, 30, 14, 'japan', 'omni', ['pork', 'gluten']),
    F('Súp miso', '1 chén', 40, 3, 4, 1.5, 'japan', 'omni', ['seafood']),
    F('Trứng hấp Nhật (chawanmushi)', '1 chén', 90, 7, 4, 5, 'japan', 'omni', ['egg', 'seafood']),
    F('Salad rong biển', '1 chén', 70, 1, 10, 3, 'japan', 'vegan', []),
    F('Cá saba nướng', '1 miếng (150g)', 300, 28, 0, 20, 'japan', 'omni', ['seafood']),
    F('Gà nướng xiên (yakitori)', '3 xiên', 250, 25, 8, 12, 'japan', 'omni', []),

    // ---------- Món Hàn ----------
    F('Cơm trộn Bibimbap', '1 tô', 600, 22, 85, 18, 'korea', 'omni', ['egg', 'beef']),
    F('Kimbap', '1 cuộn (10 miếng)', 450, 14, 70, 12, 'korea', 'omni', ['egg', 'pork']),
    F('Tokbokki (bánh gạo cay)', '1 phần', 450, 8, 90, 6, 'korea', 'omni', ['gluten', 'seafood'], 'limit', 'Nhiều tinh bột, ít đạm', 'Nửa phần, thêm trứng và chả cá'),
    F('Mì cay', '1 tô', 550, 20, 75, 18, 'korea', 'omni', ['seafood', 'gluten', 'beef'], 'limit', 'Nhiều muối, ít rau', 'Gọi thêm rau, chừa nước dùng'),
    F('Mì Ramyeon (gói Hàn)', '1 gói', 500, 10, 80, 16, 'korea', 'veg', ['gluten'], 'limit', 'Nhiều muối, chiên sẵn', 'Thêm trứng và rau, bỏ bớt gói gia vị'),
    F('Gà rán Hàn sốt cay ngọt', '4 miếng', 700, 40, 40, 40, 'korea', 'omni', ['gluten'], 'limit', 'Chiên và sốt ngọt', 'Gà nướng, bỏ da'),
    F('Ba chỉ nướng Hàn', '200g', 900, 30, 5, 85, 'korea', 'omni', ['pork'], null, '', 'Đổi sang bò nướng, ăn kèm nhiều rau cuốn'),
    F('Bò nướng Bulgogi', '200g', 450, 40, 15, 25, 'korea', 'omni', ['beef']),
    F('Canh kim chi', '1 tô', 250, 15, 15, 14, 'korea', 'omni', ['pork']),
    F('Canh rong biển', '1 tô', 120, 10, 5, 7, 'korea', 'omni', ['beef', 'seafood']),
    F('Canh đậu hũ non cay (sundubu)', '1 tô', 300, 20, 12, 18, 'korea', 'omni', ['seafood', 'egg']),
    F('Lẩu quân đội', '1 phần', 700, 30, 60, 38, 'korea', 'omni', ['pork', 'gluten'], null, '', 'Ăn nhiều đậu hũ, rau; ít mì và xúc xích'),
    F('Kim chi', '1 chén', 30, 1.5, 5, 0.5, 'korea', 'omni', ['seafood']),
    F('Mì lạnh (naengmyeon)', '1 tô', 500, 18, 90, 6, 'korea', 'omni', ['beef', 'gluten', 'egg']),
    F('Miến trộn (japchae)', '1 phần', 400, 10, 60, 14, 'korea', 'omni', ['beef']),
    F('Cơm chiên kim chi', '1 đĩa', 650, 18, 85, 25, 'korea', 'omni', ['egg', 'pork']),
    F('Gà hầm sâm', '1 tô', 700, 60, 30, 36, 'korea', 'omni', []),
    F('Bánh xèo Hàn (pajeon)', '1 cái', 450, 12, 50, 22, 'korea', 'omni', ['seafood', 'gluten', 'egg']),
    F('Chả cá Hàn (odeng)', '2 xiên', 150, 10, 15, 5, 'korea', 'omni', ['seafood', 'gluten']),

    // ---------- Món Hoa – Thái – Ấn ----------
    F('Há cảo hấp', '4 cái', 200, 10, 24, 7, 'asia', 'omni', ['seafood', 'gluten', 'pork']),
    F('Xíu mại dimsum', '4 viên', 250, 14, 12, 16, 'asia', 'omni', ['pork', 'seafood']),
    F('Bánh bao xá xíu', '1 cái', 250, 8, 40, 7, 'asia', 'omni', ['pork', 'gluten']),
    F('Vịt quay Bắc Kinh (cuốn)', '1 phần', 500, 25, 40, 26, 'asia', 'omni', ['gluten']),
    F('Lẩu cay Tứ Xuyên / mala', '1 phần', 700, 35, 30, 48, 'asia', 'omni', ['beef', 'pork'], null, '', 'Chọn nước lẩu ít dầu, nhiều rau, nấm'),
    F('Đậu phụ Tứ Xuyên (mapo tofu)', '1 đĩa', 350, 20, 12, 24, 'asia', 'omni', ['pork']),
    F('Mì xào bò kiểu Hoa', '1 đĩa', 650, 25, 75, 26, 'asia', 'omni', ['beef', 'gluten']),
    F('Pad Thái', '1 đĩa', 650, 22, 85, 24, 'asia', 'omni', ['seafood', 'egg', 'nuts']),
    F('Tom Yum', '1 tô', 250, 22, 12, 12, 'asia', 'omni', ['seafood']),
    F('Cà ri xanh gà Thái + cơm', '1 phần', 750, 30, 80, 34, 'asia', 'omni', [], null, '', 'Nửa phần cơm, ít nước cốt dừa'),
    F('Gỏi đu đủ Thái (som tam)', '1 đĩa', 150, 4, 25, 4, 'asia', 'omni', ['seafood', 'nuts']),
    F('Gà sốt bơ Ấn (butter chicken) + naan', '1 phần', 900, 40, 80, 45, 'asia', 'omni', ['dairy', 'gluten'], null, '', 'Gà tandoori + cơm, bỏ naan'),
    F('Gà nướng tandoori', '1 phần', 350, 40, 8, 17, 'asia', 'omni', ['dairy']),
    F('Cơm Biryani', '1 đĩa', 650, 25, 85, 22, 'asia', 'omni', ['dairy']),
    F('Bánh naan', '1 cái', 260, 9, 45, 5, 'asia', 'veg', ['gluten', 'dairy']),
    F('Cơm gà xào hạt điều', '1 đĩa', 650, 32, 75, 24, 'asia', 'omni', ['nuts']),
    F('Mì vằn thắn xá xíu', '1 tô', 500, 24, 65, 15, 'asia', 'omni', ['pork', 'gluten', 'egg', 'seafood']),
    F('Xôi xoài Thái', '1 phần', 450, 6, 80, 13, 'asia', 'vegan', [], 'limit', 'Nhiều đường và nước cốt dừa', 'Xoài tươi'),

    // ---------- Bánh ngọt, tráng miệng ----------
    F('Bánh su kem', '1 cái', 120, 3, 12, 7, 'bakery', 'veg', ['gluten', 'dairy', 'egg'], 'limit', 'Nhiều đường và kem béo', 'Ăn 1–2 cái thôi'),
    F('Bánh sừng bò (croissant)', '1 cái', 270, 5, 30, 14, 'bakery', 'veg', ['gluten', 'dairy', 'egg'], 'limit', 'Nhiều bơ', 'Bánh mì nguyên cám'),
    F('Bánh donut', '1 cái', 300, 4, 35, 16, 'bakery', 'veg', ['gluten', 'dairy', 'egg']),
    F('Bánh bông lan', '1 miếng', 250, 4, 35, 10, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Bánh bông lan trứng muối', '1 hộp nhỏ', 350, 8, 40, 17, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Tiramisu', '1 miếng', 400, 7, 40, 24, 'bakery', 'veg', ['dairy', 'egg', 'gluten']),
    F('Cheesecake', '1 miếng', 400, 7, 32, 28, 'bakery', 'veg', ['dairy', 'egg', 'gluten']),
    F('Bánh tart trứng', '1 cái', 220, 4, 25, 12, 'bakery', 'veg', ['egg', 'dairy', 'gluten']),
    F('Bánh waffle', '1 cái', 300, 7, 38, 13, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Pancake + siro', '3 cái', 520, 10, 85, 15, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Muffin socola', '1 cái', 400, 6, 52, 19, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Bánh quy (cookies)', '3 cái', 210, 2, 28, 10, 'bakery', 'veg', ['gluten', 'dairy']),
    F('Brownie', '1 miếng', 250, 3, 32, 13, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Macaron', '2 cái', 180, 3, 22, 9, 'bakery', 'veg', ['nuts', 'egg']),
    F('Mochi', '2 cái', 200, 2, 45, 1, 'bakery', 'vegan', []),
    F('Kem gelato', '1 viên', 150, 3, 20, 7, 'bakery', 'veg', ['dairy']),
    F('Bánh crepe sầu riêng', '1 cái', 250, 4, 30, 13, 'bakery', 'veg', ['dairy', 'egg', 'gluten']),
    F('Bánh pía', '¼ cái', 250, 4, 38, 9, 'bakery', 'veg', ['gluten', 'egg']),
    F('Bánh trung thu', '¼ cái', 220, 4, 35, 8, 'bakery', 'veg', ['gluten', 'egg', 'nuts']),
    F('Bánh mì hoa cúc', '1 lát', 200, 5, 28, 8, 'bakery', 'veg', ['gluten', 'egg', 'dairy']),
    F('Bánh bò', '1 cái', 150, 2, 30, 2, 'bakery', 'vegan', []),
    F('Bánh da lợn', '1 miếng', 180, 2, 35, 4, 'bakery', 'vegan', []),
    F('Sữa chua nếp cẩm', '1 hũ', 200, 5, 35, 5, 'bakery', 'veg', ['dairy']),
    F('Chè khúc bạch', '1 ly', 300, 6, 45, 11, 'bakery', 'veg', ['dairy', 'nuts']),
    F('Chè thái', '1 ly', 350, 4, 60, 12, 'bakery', 'veg', ['dairy']),
    F('Tàu hũ nước đường', '1 chén', 200, 8, 35, 3, 'bakery', 'vegan', []),
    F('Trái cây dầm', '1 ly', 300, 5, 55, 7, 'bakery', 'veg', ['dairy']),
    F('Rau câu', '1 miếng', 80, 0.5, 19, 0, 'bakery', 'vegan', []),
    F('Bánh flan caramel', '2 cái', 260, 8, 40, 8, 'bakery', 'veg', ['egg', 'dairy']),

    // ---------- Đồ uống, cà phê (thêm) ----------
    F('Americano', '1 ly', 10, 0.5, 1, 0, 'drink', 'vegan', []),
    F('Cà phê latte', '1 ly M', 190, 10, 18, 7, 'drink', 'veg', ['dairy'], null, '', 'Sữa ít béo, không đường'),
    F('Cappuccino', '1 ly', 130, 7, 11, 6, 'drink', 'veg', ['dairy']),
    F('Cà phê muối', '1 ly', 230, 4, 30, 10, 'drink', 'veg', ['dairy'], 'limit', 'Kem béo và đường', 'Cà phê đen, ít kem'),
    F('Cà phê cốt dừa', '1 ly', 350, 3, 45, 18, 'drink', 'veg', ['dairy'], 'limit', 'Nhiều đường và béo', 'Cà phê đen'),
    F('Matcha latte', '1 ly', 250, 8, 35, 8, 'drink', 'veg', ['dairy'], null, '', 'Ít đường, sữa không đường'),
    F('Trà sữa size L', '1 ly', 450, 4, 78, 13, 'drink', 'veg', ['dairy'], 'limit', 'Rất nhiều đường', 'Size S, 30% đường'),
    F('Trà sữa không trân châu, 30% đường', '1 ly M', 180, 3, 28, 6, 'drink', 'veg', ['dairy']),
    F('Hồng trà / trà xanh không đường', '1 ly', 2, 0, 0, 0, 'drink', 'vegan', []),
    F('Trà chanh', '1 ly', 120, 0, 30, 0, 'drink', 'vegan', []),
    F('Sinh tố xoài', '1 ly', 250, 3, 55, 3, 'drink', 'veg', ['dairy'], null, '', 'Không đường, không sữa đặc'),
    F('Sinh tố bơ không đường', '1 ly', 220, 4, 15, 16, 'drink', 'vegan', []),
    F('Nước mía', '1 ly', 180, 0, 45, 0, 'drink', 'vegan', []),
    F('Nước ép dưa hấu', '1 ly', 90, 1, 22, 0, 'drink', 'vegan', []),
    F('Nước ép cần tây', '1 ly', 40, 1, 8, 0, 'drink', 'vegan', []),
    F('Nước rau má', '1 ly', 150, 1, 36, 0, 'drink', 'vegan', [], null, '', 'Không đường'),
    F('Sữa Milo / ca cao hộp', '180ml', 130, 4, 20, 3.5, 'drink', 'veg', ['dairy']),
    F('Yakult / sữa chua uống', '1 chai', 50, 1, 11, 0, 'drink', 'veg', ['dairy']),
    F('Sữa hạt không đường', '1 hộp', 90, 3, 6, 6, 'drink', 'vegan', ['nuts']),
    F('Kombucha', '1 chai', 50, 0, 12, 0, 'drink', 'vegan', []),
    F('Nước tăng lực', '1 lon', 110, 0, 28, 0, 'drink', 'vegan', []),
    F('Nước điện giải', '1 chai 500ml', 120, 0, 30, 0, 'drink', 'vegan', [], null, '', 'Nước lọc nếu tập dưới 60 phút'),
    F('Rượu vang đỏ', '1 ly 150ml', 125, 0, 4, 0, 'drink', 'vegan', [], 'limit', 'Calo rỗng từ cồn', 'Tối đa 1 ly'),
    F('Soju', '1 chai', 400, 0, 0, 0, 'drink', 'vegan', [], 'limit', 'Calo rỗng từ cồn', 'Uống ít, xen kẽ nước lọc'),
    F('Cocktail (mojito…)', '1 ly', 220, 0, 25, 0, 'drink', 'vegan', [], 'limit', 'Cồn và đường', 'Nước có ga + chanh, không đường'),
    F('Bia không cồn', '1 lon', 60, 0.5, 13, 0, 'drink', 'vegan', ['gluten']),

    // ---------- Ăn vặt (thêm) ----------
    F('Bắp xào bơ', '1 ly', 300, 6, 40, 14, 'snack', 'veg', ['dairy'], null, '', 'Bắp luộc'),
    F('Cá viên chiên', '10 viên', 300, 12, 25, 17, 'snack', 'omni', ['seafood', 'gluten'], null, '', 'Cá viên luộc / nướng'),
    F('Xúc xích chiên', '2 cây', 300, 10, 6, 26, 'snack', 'omni', ['pork']),
    F('Khoai lang chiên', '1 phần', 350, 3, 45, 18, 'snack', 'vegan', [], null, '', 'Khoai lang luộc / nướng'),
    F('Bánh gạo', '4 cái', 120, 2, 24, 2, 'snack', 'vegan', []),
    F('Rong biển ăn liền', '1 gói 5g', 25, 1, 1, 2, 'snack', 'vegan', []),
    F('Hạt hướng dương', '30g', 170, 6, 6, 15, 'snack', 'vegan', ['nuts']),
    F('Hạt dẻ cười', '30g', 160, 6, 8, 13, 'snack', 'vegan', ['nuts']),
    F('Thanh granola', '1 thanh', 190, 4, 29, 7, 'snack', 'vegan', ['nuts', 'gluten']),
    F('Thanh protein bar', '1 thanh', 200, 20, 22, 7, 'snack', 'veg', ['dairy', 'nuts']),
    F('Socola đen 70%', '20g', 120, 2, 9, 9, 'snack', 'vegan', [], null, 'Chất chống oxy hóa, ăn 1–2 miếng'),
    F('Bánh tráng nướng mắm ruốc', '1 cái', 250, 6, 35, 10, 'snack', 'omni', ['seafood']),
    F('Trứng gà nướng', '2 quả', 160, 12, 2, 11, 'snack', 'veg', ['egg']),
    F('Bánh snack que', '1 gói', 150, 2, 18, 8, 'snack', 'vegan', ['gluten']),
    F('Bánh quy giòn (cracker)', '4 cái', 130, 2, 20, 5, 'snack', 'vegan', ['gluten'])
  ];
})();

BRAIN.MEAL_TIMES = {2: '2 bữa trong khung 8 tiếng, ví dụ 11:30 và 19:00', 3: '3 bữa: khoảng 7:00, 12:00 và 18:30', 5: '3 bữa chính (7:00, 12:00, 18:30) và 2 bữa phụ nhỏ (10:00, 15:30)'};
// Ăn quanh giờ tập: trước tập (tinh bột dễ tiêu), sau tập (đạm)
BRAIN.WORKOUT_FUEL = {
  am: {pre: '30 phút trước khi tập', post: 'ăn sáng ngay sau tập'},
  noon: {pre: 'bữa phụ lúc 10:00', post: 'bữa trưa ngay sau tập'},
  pm: {pre: '60–90 phút trước khi tập (khoảng 16:00)', post: 'bữa tối sau tập'},
  any: {pre: '60–90 phút trước khi tập', post: 'trong vòng 1–2 giờ sau tập'}
};
